### ISSUE TITLE
SCC can not start with go.sh in mac M1

### ISSUE THREAD

**Issue by horsemanjackyliu** [SAP-docs/btp-connectivity#4]
### Issue description

run go.sh
end with error .

scc % go.sh
using java /opt/homebrew/Caskroom/sapmachine17-jdk/17.0.7/sapmachine-jdk-17.0.7.jdk/contents/Home/bin/java
Generating initial key store for Administration UI
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib: dlopen(/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib, 0x0001): tried: '/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib' (code signature in <CC74ED19-7E73-3C4C-9E67-9E4ED584B836> '/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib' (no such file), '/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib' (code signature in <CC74ED19-7E73-3C4C-9E67-9E4ED584B836> '/Users/I501000/Documents/devtools/scc/lib/native/libsapscc20jni.dylib' not valid for use in process: library load disallowed by system policy)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sap.scc.jni.NativeLibrariesInitializer.initialize(NativeLibrariesInitializer.java:36)
	at com.sap.scc.jni.SecStoreAccess.main(SecStoreAccess.java:223)
keytool error: java.lang.Exception: Keystore password must be at least 6 characters
java.lang.Exception: Keystore password must be at least 6 characters
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1028)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:423)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:416)
Was not able to create the keystore properly

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Installation on Apple macOS

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/installation-on-mac-os-x?locale=en-US

**Comment by horsemanjackyliu** [comment]
system also give an alert as the picture .

![image](https://github.com/SAP-docs/btp-connectivity/assets/74337345/c837c3d9-1a56-4ed3-953c-6024c227f972)

**Comment by horsemanjackyliu** [comment]
Resolved

**Comment by Frank1Mueller** [comment]
Hi horsemanjackyliu,

good to hear this :)

Best regards

Frank

**Comment by nkappler** [comment]
@horsemanjackyliu how did you resolve this? I'm facing the same issue
